### ISSUE TITLE
Combine MRE with other  extensions

### ISSUE THREAD

**Issue by alfgil** [sorengranfeldt/mre#10]
Feature Request:

MRE-product should be able to load and execute code in external DLLs, typically an existing MVextension.dll.

MIM-2016 (and earlier versions) can only have one DLL defined for "Metaverse Rule Extension". If this DLL is already being used, it is a blocking situation with regards to bringing thedynamic flexibility of MRE into the configuration. 

I wish MRE can have it's existing rule methods extended with the ability to execute another DLL for provisioning against one or more spcific MA's and still use its own rules for other MA's. This would significantly add to the flexibility and usability of the MRE product, in particular for old FIM/MIM installations with an exisiting MVextension.dll which can not be easily abandoned. 

MRE with this funcionality could then maybe also completely replace the old "Metverse Router" solution that was introduced by Microsoft many years ago.

**Comment by sorengranfeldt** [comment]
If I put out a draft release shortly, will you be able to test and give feedback before final release?

**Comment by alfgil** [comment]
I'd love to!

**Comment by sorengranfeldt** [comment]
There is a draft release out. See if it fits your needs. Input are very welcome - also for documentation :-)

Find it [here](https://github.com/sorengranfeldt/mre/releases/tag/v1.2.5.0)

**Comment by alfgil** [comment]
Hi,
Generally, it seems to be doing exactly what I was hoping for, but I have a few questions. See attached PDF.
[MRE-test01.pdf](https://github.com/sorengranfeldt/mre/files/2379177/MRE-test01.pdf)
[MRE-test01.pdf](https://github.com/sorengranfeldt/mre/files/2379232/MRE-test01.pdf)

(New file attached - drop the first one)

**Comment by sorengranfeldt** [comment]
Quick answers to above PDF
1) Fixed in Wiki. Thanks for noticing.
2) Rule names are only for convenience. Can be duplicated
3) New tracing functionality has been added; old registry key is deprecated and not supported. I updated the Logging page in the Wiki. Thanks for noticing.
4) You can only have one target MA per rule. No check done for this. Guess MRE will pick the first. You need a rule per MA.

**Comment by alfgil** [comment]
Thank you, looks better now, but I have attached another file for you. I have a feeling this is in our own legacy code, but let me know what you think. Just remember; there are no errors when using the legacy MVextension directly.
[MRE-test02.pdf](https://github.com/sorengranfeldt/mre/files/2379544/MRE-test02.pdf)

**Comment by sorengranfeldt** [comment]
Theres a logging statement in MRE that refers to the displayName attribute. I guess the error occurs when the displayname attribute is not bound to particular objects. It’s not your code. It’s MRE. Are things otherwise working as expected besides an error being logged ? If so, I’ll fix it in next release

**Comment by sorengranfeldt** [comment]
Could you try binding the displayName attribute to the object in question in the Metaverse Designer and see if error goes away?

**Comment by sorengranfeldt** [comment]
I've changed the logging statement to not use the displayName and added a new .zip to the release. 

Could you test that - get the [1.2.5.1 zip here](https://github.com/sorengranfeldt/mre/releases/tag/v1.2.5.0)

**Comment by alfgil** [comment]
Perfect! Provisioning now updates both AD and our Shift-planning system for both people and their positions!  I still have some work to do to integrate with other custom MA's, but this looks very promising! Thank you very much!
I have attached a small part of a log-file, and I'd appreciate if you have the time to explain why the rule "GAT-Job" add more log-information than the two rules for "AD-Person" and "GAT-Person". I made them all exactly the same, except they trigger on different object in Metaverse. RTFM?
[mre.20180914-001.LOG](https://github.com/sorengranfeldt/mre/files/2382165/mre.20180914-001.LOG)

**Comment by sorengranfeldt** [comment]
Great. I cannot see why there is a difference in logging but looks like something with some rules having conditions and others not. I dont think you need to worry about that if things are working. I would have to spend time on your installation to further investigate and right now I'm quite booked :-)

**Comment by sorengranfeldt** [comment]
If there is nothing further by tomorrow, I'll close this thread - or you can do it if you're happy with the current version
