### ISSUE TITLE
RuleFilesAlternativePath

### ISSUE THREAD

**Issue by alfgil** [sorengranfeldt/mre#12]
When using this feature, the path to the legacy extension-DLL is also changed to the same alternative path. According to the documentation, the path to the external DLL is [fim]\Extensions if no full path is given. This is not correct if RuleFilesAlternativePath is given. 
This is easily solved by giving full path to the extension DLL in rules-file, but you should probably add a note in the docs.

**Comment by sorengranfeldt** [comment]
Note added to Wiki page. Thank you for noticing.
