### ISSUE TITLE
No example for DeprovisionAll?

### ISSUE THREAD

**Issue by lehtoj** [sorengranfeldt/mre#14]
Hi.

Could we please get an example for action DeprovisionAll?

I am not certain whether this action is exactly the same as Deprovision, except for action name itself. Why does DeprovisionAll require TargetManagementAgentName?

**Comment by sorengranfeldt** [comment]
It will deprovision the MVEntry from all connected MA's. It does not use the TargetManagementAgentName as such. I dont have an example right now. You can also do individual deprov's per MA if conditions are different. It all depends on your scenario.

**Comment by lehtoj** [comment]
I know the difference between the two, I meant the rule syntax differences between Deprovision and DeprovisionAll, if there are any in fact. Especially considering I got an error when I tried DeprovisionAll without TargetManagementAgentName.

**Comment by sorengranfeldt** [comment]
No syntax. But I guess in the current version an MA is required
