### ISSUE TITLE
Conditional bitmask request

### ISSUE THREAD

**Issue by zbnet0** [sorengranfeldt/mre#18]
We need  to be able to create a rule that allows to match an attribute with a bitwise map, so (say) sync only objects that had UserAccountControl with bit 2 not set (enabled accounts)

**Comment by sorengranfeldt** [comment]
I'll have a look at implementing this in the next version.

**Comment by zbnet0** [comment]
Fabulous - thanks so much  :-)

________________________________

**Comment by sorengranfeldt** [comment]
Included in latest version just released - https://github.com/sorengranfeldt/mre/releases/tag/1.2.5.7

**Comment by zbnet0** [comment]
This is awesome - thanks so much  :-)

Kevin


________________________________
