### ISSUE TITLE
UserProxy provision

### ISSUE THREAD

**Issue by VVincent0** [sorengranfeldt/mre#2]
Hello,

I am trying to Provision UserProxy to an AD LDS intance, as you know, you need to set the objectSID. 
You can’t simply add an atribute flow to the MA objectSid(MV)==> objectSid(CS) because it is a « read-only » attribute so you need to do this when you use provision code (see attached image)
![extension-code-1](https://user-images.githubusercontent.com/29401383/28063336-1e3a4852-6631-11e7-9a48-e9e35bb70d90.jpg)

So i tried to write in my  « xxx.fil.mre.xml » config file this :

`<AttributeFlowBase xsi:type="AttributeFlowAttribute">
                              <Source>objectSid</Source>
                              <Target> objectSid </Target>
               </AttributeFlowBase>`

When i export my object to the LDS instance i have the following error :
« constraint-violation » « multiple values were specified for an attribute that can have only one value »

Do you have any idea to work around this ?

Thank you very much for all your work

**Comment by ryannewington** [comment]
I have this working in my environment currently. Here's the full MRE rule
```
<Rule>
      <Name>Provision user ==> Lds</Name>
      <Description>Provisions a user to LDS</Description>
      <TargetManagementAgentName>LDS</TargetManagementAgentName>
      <Enabled>true</Enabled>
      <SourceObject>user</SourceObject>
      <TargetObject>idmUserProxy</TargetObject>
      <Action>Provision</Action>
      <Conditions>
        <ConditionBase xsi:type="ConditionMatch">
          <Description>Only if person has a provisionToLds flag set to true</Description>
          <MVAttribute>provisionToLds</MVAttribute>
          <Pattern>True</Pattern>
        </ConditionBase>
        <ConditionBase xsi:type="ConditionIsPresent">
          <Description>Check if csObjectID is present</Description>
          <MVAttribute>csObjectID</MVAttribute>
        </ConditionBase>
        <ConditionBase xsi:type="ConditionIsPresent">
          <Description>Check if objectSid is present</Description>
          <MVAttribute>objectSid</MVAttribute>
        </ConditionBase>
      </Conditions>
      <InitialFlows>
        <AttributeFlowBase xsi:type="AttributeFlowAttribute">
          <Source>objectSid</Source>
          <Target>objectSid</Target>
        </AttributeFlowBase>
        <AttributeFlowBase xsi:type="AttributeFlowAttribute">
          <Source>ldsDN</Source>
          <Target>[DN]</Target>
        </AttributeFlowBase>
      </InitialFlows>
    </Rule>
```

Is the constraint violation actually coming from the objectSID attribute or something else?

**Comment by VVincent0** [comment]
Yes i am pretty sure that the constraint is on the objectSid attribute because it works when i only set the DN.


It is possible that the error comes from the custom class i use (herited from userproxyfull).


I'll look in that direction.


Thank you for your help.


VUILLAUME Vincent

________________________________
De : Ryan Newington <notifications@github.com>
Envoyé : mardi 11 juillet 2017 12:13:48
À : sorengranfeldt/mre
Cc : VUILLAUME Vincent; Author
Objet : Re: [sorengranfeldt/mre] UserProxy provision (#2)


I have this working in my environment currently. Here's the full MRE rule

<Rule>
      <Name>Provision user ==> Lds</Name>
      <Description>Provisions a user to LDS</Description>
      <TargetManagementAgentName>LDS</TargetManagementAgentName>
      <Enabled>true</Enabled>
      <SourceObject>user</SourceObject>
      <TargetObject>idmUserProxy</TargetObject>
      <Action>Provision</Action>
      <Conditions>
        <ConditionBase xsi:type="ConditionMatch">
          <Description>Only if person has a provisionToLds flag set to true</Description>
          <MVAttribute>provisionToLds</MVAttribute>
          <Pattern>True</Pattern>
        </ConditionBase>
        <ConditionBase xsi:type="ConditionIsPresent">
          <Description>Check if csObjectID is present</Description>
          <MVAttribute>csObjectID</MVAttribute>
        </ConditionBase>
        <ConditionBase xsi:type="ConditionIsPresent">
          <Description>Check if objectSid is present</Description>
          <MVAttribute>objectSid</MVAttribute>
        </ConditionBase>
      </Conditions>
      <InitialFlows>
        <AttributeFlowBase xsi:type="AttributeFlowAttribute">
          <Source>objectSid</Source>
          <Target>objectSid</Target>
        </AttributeFlowBase>
        <AttributeFlowBase xsi:type="AttributeFlowAttribute">
          <Source>ldsDN</Source>
          <Target>[DN]</Target>
        </AttributeFlowBase>
      </InitialFlows>
    </Rule>


Is the constraint violation actually coming from the objectSID attribute or something else?

**Comment by VVincent0** [comment]
Well, that was indeed due to the custom class i use, now i have the following error "A value for the attribute was not in the acceptable range of values.", and i don't think the DLL is to blame.

Thank you
