### ISSUE TITLE
ConditionAfter

### ISSUE THREAD

**Issue by SaeedPrez** [sorengranfeldt/mre#20]
I noticed in the docs for **ConditionAfter** it says:

> This condition can be used to check whether a date/time in a metaverse attribute is after the current date/time.

..but the code is actually the reverse:

`bool returnValue = now > value;`

Same kind of error with **ConditionBefore** I believe.

**Comment by sorengranfeldt** [comment]
I see your point. It is a matter of perspective, so it is basically the documentation that is incorrect. I'll have a look at that and correct it soon.

Happy holidays.

**Comment by sorengranfeldt** [comment]
Documentation has been updated
