### ISSUE TITLE
Handling ObjectAlreadyExistsException

### ISSUE THREAD

**Issue by NileshGhodekar** [sorengranfeldt/mre#22]
Hi Søren,

Is there a way to handle ObjectAlreadyExistsException during provisioning without writing your own code like auto-incrementing the CN on DN collision?

Thanks!

**Comment by sorengranfeldt** [comment]
There is nothing built into the MRE for this. You have to have import or generate the unique CN. You could have a look at the Helpers in the Wiki to see if that could assist you

**Comment by NileshGhodekar** [comment]
Thanks! Will close this issue now.
