### ISSUE TITLE
ConditionalRename does not work in a "Provision" action

### ISSUE THREAD

**Issue by ruliane** [sorengranfeldt/mre#25]
According to https://github.com/sorengranfeldt/mre/wiki/ConditionalRename, it is possible to provision and rename AD objects in a single rule.
I want to take advantage of this to force the CN of objects.

The following rule works for provisioning but does not renames mis-named objects:
```
<Rule>
  <Name>AD-Prov</Name>
  <TargetManagementAgentName>AD</TargetManagementAgentName>
  <Enabled>true</Enabled>
  <SourceObject>person</SourceObject>
  <TargetObject>user</TargetObject>
  <Action>Provision</Action>
  <Conditions>
    <ConditionBase xsi:type="ConditionIsPresent">
    <Description></Description>
    <MVAttribute>accountName</MVAttribute>
    </ConditionBase>
  </Conditions>
  <InitialFlows>
    <AttributeFlowBase xsi:type="AttributeFlowConstant">
      <EscapedCN>CN=#mv:accountname#</EscapedCN>
      <Constant>#param:EscapedCN#,OU=Users,OU=T2,DC=contoso,DC=local</Constant>
      <Target>[DN]</Target>
    </AttributeFlowBase>
    <AttributeFlowBase xsi:type="AttributeFlowConstant">
      <Constant>514</Constant>
      <Target>userAccountControl</Target>
    </AttributeFlowBase>
    <AttributeFlowBase xsi:type="AttributeFlowAttribute">
      <UppercaseTargetValue>true</UppercaseTargetValue>
      <Source>accountName</Source>
      <Target>sAMAccountName</Target>
    </AttributeFlowBase>
  </InitialFlows>
  <ConditionalRename>
    <NewDNValue>CN=#mv:accountName#,OU=Users,OU=T2,DC=contoso,DC=local</NewDNValue>
    <DNAttribute>[DN]</DNAttribute>
    <Conditions>
      <ConditionBase xsi:type="ConditionIsPresent">
      <Description></Description>
      <MVAttribute>accountName</MVAttribute>
    </ConditionBase>
    </Conditions>
  </ConditionalRename>
</Rule>
```

If I change `<Action>Provision</Action>` to `<Action>Rename</Action>` the rule works, but - of course - does not provision users.
Do I miss something?

**Comment by sorengranfeldt** [comment]
You can't do that in a single rule. You have to have a Provision rule and a separate rename rule for already created objects that you want to move around.

**Comment by ruliane** [comment]
Hello @sorengranfeldt ,

Thank you for this answer ; it works like a charm with two rules. 👌🏼

That said, I can't understand the following statement on the ConditionalRename page:
> _*NOTE*_ - You can include the ConditionRename element in a 'Provision' action and that rule could then also rename an existing connector if conditions match.

Do I misunderstand it or is it simply wrong?
