### ISSUE TITLE
Rules located after a Rename rule are ignored

### ISSUE THREAD

**Issue by ruliane** [sorengranfeldt/mre#26]
Hello,

I have a strange issue when combining several rules on the same Management Agent.

If FIM.MRE.xml states the following:
- Rule 1 : Provision
- Rule 2 : Deprovision
- Rule 3 : Rename
All three rules are handled by MRE.

If FIM.MRE.xml states the following:
- Rule 1 : Provision
- Rule 2 : Rename
- Rule 3 : Deprovision

Rules 1 and 2 are treated but rule 3 is ignored.

It looks like any "Rename" rule prevents any further treatment on the same MA. Is it an expected behavior?

**Comment by sorengranfeldt** [comment]
Only one rule is executed per MA and connector at a time/per run - this is by design and for performance

**Comment by sorengranfeldt** [comment]
Also, the logic can be seen in the Provision method in the code. If there is a provision, no other rules are processed in the latest version

**Comment by ruliane** [comment]
I'll take a look at the Provision method.
As I can see in debug logs, Deprovision and Rename are processed even after Provision:
![image](https://github.com/sorengranfeldt/mre/assets/5471186/2266f273-825d-4418-b48e-b50222112cab)

**Comment by sorengranfeldt** [comment]
Yes, that's correct - but if there is no connector only Provision is processed, but if there is a connector all are processed (as I remember). That code will guide to more understanding.

**Comment by ruliane** [comment]
> if there is no connector only Provision is processed

That makes sense.


As I understand, the code does the following:

- The `for` loop exists as soon as a **Provision** action is triggered:
```
                        if (rule.Action == RuleAction.Provision)
                        {
                                [...]
                                // Don't need to process any more rules
                                // as we have just newly provisioned
                                executedMAs.Add(ma.Name);
                                continue;
                        }
```
- The **Rename** block works a similar way:
```
                        if (rule.Action == RuleAction.Rename)
                        {
                            [...]
                            if (hasRenamed)
                            {
                                executedMAs.Add(ma.Name);
                                continue;
                            }
                        }
```

- and the **Deprovision** block as well:
```
                        else if (rule.Action == RuleAction.Deprovision)
                        {
                            [...]
                            if (hasDeleted)
                            {
                                executedMAs.Add(ma.Name);
                                continue;
                            }
                        }
```

When exiting the **Rename** block too early, this logic prevents subsequent **Deprovision** actions to be played.

In my case, the **Rename** action is always `true` (this is to force user accounts in the right location), but the **Deprovision** action should have priority over the **Rename** action. With the current logic, I see two way to achieve this:
- either by switching actions: if **Deprovision** appears before **Rename** in the config file, it is triggered, then the `for` loop exists.
- or by specifying exclusive conditions between **Rename** and **Deprovision** actions. The **Rename** condition would return `false`, and the **Deprovision** action would be triggered next.

Which one do you think is the better solution?

I suggest to explain this logic on the wiki (and I might open a PR soon).
