### ISSUE TITLE
Add condition MultivalueIsPresent

### ISSUE THREAD

**Issue by sorengranfeldt** [sorengranfeldt/mre#3]

**Comment by sorengranfeldt** [comment]
Create new condition to allow check for a value in a multivalued string

**Comment by sorengranfeldt** [comment]
Still planning for this

**Comment by thomashouston** [comment]
Hey Soren, just wondering if there's an ETA for this 'MultiValueIsPresent' condition as I'd like to use it in a new MIM project.. Thanks!

**Comment by sorengranfeldt** [comment]
Hi, haven't planned spending time on it just now. Shouldn't be a huge add-on though so maybe I can have a look at it shortly. I would accept a pull request for it if you have an option to add it your self ?

**Comment by sorengranfeldt** [comment]
Also, have a look at this - https://github.com/sorengranfeldt/mre/pull/16 - a ConditionContains was added that may satisfy your issue ? It is missing documentation though and that is why you may not have noticed it

**Comment by thomashouston** [comment]
Thanks Soren - 'ConditionContains' worked perfectly.
