### ISSUE TITLE
Installation steps are not clear

### ISSUE THREAD

**Issue by maxgaulhofer** [sorengranfeldt/mre#6]
how do I install MRE? Where can I build the file 'FIM.MRE.dll'? Do I need to build this my self using visual studio? What settings are required?

Maybe a good idea to put a hyperlink in the readme to the documentation or build steps

**Comment by sorengranfeldt** [comment]
There is a DLL in the Release downloads under Code.

Are you avle to find that?

Med venlig hilsen
Søren Granfeldt

On 15 Jun 2018, at 11.48, maxgaulhofer <notifications@github.com<mailto:notifications@github.com>> wrote:


how do I install MRE? Where can I build the file 'FIM.MRE.dll'? Do I need to build this my self using visual studio? What settings are required?

Maybe a good idea to put a hyperlink in the readme to the documentation or build steps

**Comment by maxgaulhofer** [comment]
Yes i found it thanks. But install steps could be clearer

**Comment by sorengranfeldt** [comment]
I'll have a look at the doc on next release cycle
