### ISSUE TITLE
MRE in combination with other MetaverseExtensions

### ISSUE THREAD

**Issue by alfgil** [sorengranfeldt/mre#9]
Is there a way to use MRE in combination with another "MVextension" DLL?
We provision users to a number of systems - all custom built MA's and managed through one big MVextension.dll. I wish it was possible to continue to use it in combination with MRE. Can I do that?

**Comment by sorengranfeldt** [comment]
In the current version, this is not possible. I have, however, a wish to be able to do this myself from time to time. So I'm willing to look into this feature. I was considering doing a rule type addition to allow for MRE to load and a call to another DLL. 

Does that seem like an option for you? If so, could you maybe do a feature request here and I'll try to prioritize it

**Comment by alfgil** [comment]
I sure will! I have considered using the old MetaverseRouter code I found in a Codeplex Archive, but to have this feature inside MRE would be a lot more attractive!
